export const LOAD_KEYS = 'LOAD_KEYS';
export const LOAD_RESULTS = 'LOAD_RESULTS';
export const RESET_RESULTS = 'RESET_RESULTS';
export const ADD_RESULT = 'ADD_RESULT';
export const SELECT_PREDICTION = 'SELECT_PREDICTION';
